#ifndef _MEGA_COMMON_ERRCODE_H_
#define _MEGA_COMMON_ERRCODE_H_


enum adm_operate_errcode {
    ASMEGA_ADM_OK = 0,
    ASMEGA_ADM_CMD_ERR,

    /* PVT_ADMIN*/
    ASMEGA_ADM_TNL_ADD_ERROR = -100,
    ASMEGA_ADM_TNL_DEL_ERROR,
    ASMEGA_ADM_TNL_SET_ERROR,
    ASMEGA_ADM_PARSE_TUNNEL_ERROR,
    ASMEGA_ADM_PARSE_VIEW_ERROR,
    ASMEGA_ADM_SOCKET_BUSY,
    ASMEGA_ADM_CREATE_SOCKET_ERROR,
    ASMEGA_ADM_GET_SOCKOPT_FAILED_ERROR,
    ASMEGA_ADM_GET_SOCKOPT_BUFF_SIZE_ERROR,
    ASMEGA_ADM_GET_SOCKOPT_TNL_NUM_ERROR,
    ASMEGA_ADM_SET_SOCKOPT_BIND_ERROR,
    ASMEGA_ADM_SET_SOCKOPT_UNBIND_ERROR,
    ASMEGA_ADM_SET_SOCKOPT_CLEAR_ERROR,
    ASMEGA_ADM_SET_SOCKOPT_TNL_NUM_ERROR,
    ASMEGA_ADM_TNL_LIST_NULL_ERROR,
    ASMEGA_ADM_TNL_NUM_NULL_ERROR,

    /* PVT_KNL */
    ASMEGA_KNL_TNL_DB_ALLOC_ERROR = -200,
    ASMEGA_KNL_TNL_ADD_ERROR,
    ASMEGA_KNL_TNL_SET_ERROR,
    ASMEGA_KNL_TNL_DEL_ERROR,
    ASMEGA_KNL_TNL_SET_ALL_ERROR,
    ASMEGA_KNL_TNL_SET_ALL_NOT_SORT_ERROR,
    ASMEGA_KNL_SET_SOCKOPT_TNL_NUM_ERROR,
    ASMEGA_KNL_SET_SOCKOPT_COPY_ERROR,
    ASMEGA_KNL_GET_SOCKOPT_BUF_LEN_ERROR,
    ASMEGA_KNL_GET_SOCKOPT_COPY_ERROR,
};

#endif
