MOD_OBJ = test.o \
		  ../knl/cache.o\
		  ../knl/lock.o\
		  ../knl/control.o\
		  ../knl/manage.o\
		  ../knl/stats.o\
		  ../knl/timer.o\
		  ../knl/dataplane.o\
		  ../knl/qpslimit.o\
		  testcase.o

MOD = dnsmegatest

include $(DNS_TRUNK)/mk/Makefile.mod
