#ifndef _ADNS_COMMON_ERRCODE_H_
#define _ADNS_COMMON_ERRCODE_H_


#include <errno.h>


#define ERRBASE 100
#define err2code(x) (-(ERRBASE + (x)))
#define adns_map_errno(err...) map_errno(ADNS_ERROR, err);


enum adns_parse_errcode {
    ADNS_RESPONSE_PARSE_SECTION_PTR_NULL = -100,
    ADNS_RESPONSE_PARSE_SECTION_QNAME_ERROR,

    ADNS_RESPONSE_PARSE_SECTION_SOA_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_SOA_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_A_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_A_IP_CONVERT_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_A_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_AAAA_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_AAAA_IP_CONVERT_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_AAAA_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_DOMAIN_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_DOMAIN_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_MX_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_MX_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_TXT_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_TXT_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_SRV_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_SRV_DATA_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_CAA_PTR_ERROR,
    ADNS_RESPONSE_PARSE_SECTION_CAA_DATA_ERROR
};


enum adns_adm_operate_errcode {
    ADNS_ADM_OK = 0,
    ADNS_ADM_ERROR = -1,
    ADNS_ADM_SOCKET_BUSY = -2,
    ADNS_ADM_SOCKET_ERROR = -3,

    ADNS_ADM_PARSE_ERROR = -100,
    ADNS_ADM_PARSE_VMFILE_ERROR,
    ADNS_ADM_PARSE_BATCH_ERROR,
    ADNS_ADM_PARSE_IP_ERROR,
    ADNS_ADM_PARSE_ZONE_ERROR,
    ADNS_ADM_PARSE_DOMAIN_ERROR,
    ADNS_ADM_PARSE_RDATA_ERROR,
    ADNS_ADM_PARSE_CLASS_ERROR,
    ADNS_ADM_PARSE_TYPE_ERROR,
    ADNS_ADM_PARSE_TTL_ERROR,
    ADNS_ADM_PARSE_WEIGHT_ERROR,
    ADNS_ADM_PARSE_VIEW_ERROR,
    ADNS_ADM_PARSE_LOG_SWITCH_ERROR,
    ADNS_ADM_PARSE_LOG_LEVEL_ERROR,
    ADNS_ADM_PARSE_LOG_ROTATE_SIZE_ERROR,
    ADNS_ADM_PARSE_LOG_ROTATE_COUNT_ERROR,
    ADNS_ADM_PARSE_BATCH_ZONE_ERROR,
    ADNS_ADM_PARSE_BATCH_DOMAIN_ERROR,
    ADNS_ADM_PARSE_BATCH_VIEW_ERROR,
    ADNS_ADM_PARSE_BATCH_TTL_ERROR,
    ADNS_ADM_PARSE_BATCH_WEIGHT_ERROR,
    ADNS_ADM_PARSE_BATCH_SOA_DATA_ERROR,
    ADNS_ADM_PARSE_ZONE_QPS_ERROR,
    ADNS_ADM_PARSE_ZONE_BPS_ERROR,
    ADNS_ADM_PARSE_DOMAIN_QPS_ERROR,
    ADNS_ADM_PARSE_DOMAIN_BPS_ERROR,
    ADNS_ADM_PARSE_INTERVAL_ERROR,
    ADNS_ADM_PARSE_CUSTOM_VIEW_ID_ERROR,
    ADNS_ADM_PARSE_KEY_TAG_ERROR,

    /* ADNS_ADMIN ZONE */
    ADNS_ADMIN_ADD_ZONE_CONVERT_ZONE_ERROR = -200,
    ADNS_ADMIN_ADD_ZONE_ALLOC_ERROR,
    ADNS_ADMIN_ADD_ZONE_LENGTH_ERROR,
    ADNS_ADMIN_ADD_ZONE_TO_ZONEDB_ERROR,
    ADNS_ADMIN_DEL_ZONE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_DEL_ZONE_ERROR,
    ADNS_ADMIN_EDIT_ZONE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_EDIT_ZONE_NOT_FOUND_ERROR,
    ADNS_ADMIN_EDIT_ZONE_LENGTH_ERROR,
    ADNS_ADMIN_LIST_ZONE_ERROR,
    ADNS_ADMIN_LIST_ZONE_ALLOC_ERROR,
    ADNS_ADMIN_LIST_ZONE_CHANGE_ERROR,
    ADNS_ADMIN_LIST_ZONE_MEMORY_LACK_ERROR,
    ADNS_ADMIN_DEL_ZONE_RCU_REGISTER_ERROR,
    ADNS_ADMIN_ADD_ROUTE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_ADD_ROUTE_ZONEDB_NULL,
    ADNS_ADMIN_ADD_ROUTE_ZONE_NOT_EXIST,
    ADNS_ADMIN_ADD_ROUTE_MEMORY_ERROR,
    ADNS_ADMIN_ADD_ROUTE_IPLIB_FILE_ERROR,
    ADNS_ADMIN_DEL_ROUTE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_DEL_ROUTE_ZONEDB_NULL,
    ADNS_ADMIN_DEL_ROUTE_ZONE_NOT_EXIST,
    ADNS_ADMIN_DEL_ROUTE_RCU_REGISTER_ERROR,
    ADNS_ADMIN_RELOAD_ROUTE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_RELOAD_ROUTE_ZONEDB_NULL,
    ADNS_ADMIN_RELOAD_ROUTE_ZONE_NOT_EXIST,
    ADNS_ADMIN_RELOAD_ROUTE_MEMORY_ERROR,
    ADNS_ADMIN_RELOAD_ROUTE_IPLIB_FILE_ERROR,
    ADNS_ADMIN_DUMP_ROUTE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_DUMP_ROUTE_ZONEDB_NULL,
    ADNS_ADMIN_DUMP_ROUTE_ZONE_NOT_EXIST,
    ADNS_ADMIN_DUMP_ROUTE_OPEN_DUMP_FILE_ERROR,
    ADNS_ADMIN_DUMP_ROUTE_DUMP_IP_SEG_ERROR,


    /* ADNS_ADMIN RR */
    ADNS_ADMIN_ADD_RR_CONVERT_ZONE_ERROR = -300,
    ADNS_ADMIN_ADD_RR_FIND_ZONE_ERROR,
    ADNS_ADMIN_ADD_RR_TYPE_ERROR,
    ADNS_ADMIN_ADD_RR_DOMAIN_ERROR,
    ADNS_ADMIN_ADD_RR_CREATE_NODE_ERROR,
    ADNS_ADMIN_ADD_RR_NEW_RRSET_ERROR,
    ADNS_ADMIN_ADD_RR_SET_RRSET_ERROR,
    ADNS_ADMIN_ADD_RR_NEW_RDATA_CTL_ERROR,
    ADNS_ADMIN_ADD_RR_CNAME_EXIST_ERROR,
    ADNS_ADMIN_ADD_RR_ADD_RDATA_ERROR,
    ADNS_ADMIN_EDIT_RR_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_EDIT_RR_FIND_ZONE_ERROR,
    ADNS_ADMIN_EDIT_RR_TYPE_ERROR,
    ADNS_ADMIN_EDIT_RR_DOMAIN_ERROR,
    ADNS_ADMIN_EDIT_RR_FIND_NODE_ERROR,
    ADNS_ADMIN_EDIT_RR_GET_RRSET_ERROR,
    ADNS_ADMIN_EDIT_RR_GET_RDATA_CTL_ERROR,
    ADNS_ADMIN_EDIT_RR_MODIFY_RDATA_ERROR,
    ADNS_ADMIN_DEL_DOMAIN_ALL_DOMAIN_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_FIND_ZONE_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_TYPE_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_DOMAIN_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_FIND_NODE_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_FIND_RRSET_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_FIND_RDATA_CTL_ERROR,
    ADNS_ADMIN_LIST_DOMAIN_FILL_RDATA_ERROR,
    ADNS_ADMIN_ADD_RR_INTERNAL_ERROR,

    ADNS_ADMIN_SCHEDULE_CONVERT_ZONE_ERROR = -400,
    ADNS_ADMIN_SCHEDULE_FIND_ZONE_ERROR,
    ADNS_ADMIN_SCHEDULE_DOMAIN_ERROR,
    ADNS_ADMIN_SCHEDULE_FIND_NODE_ERROR,
    ADNS_ADMIN_SCHEDULE_FIND_RRSET_ERROR,
    ADNS_ADMIN_SCHEDULE_FIND_VIEW_ERROR,
    ADNS_ADMIN_SCHEDULE_EMPTY_VIEW,
    ADNS_ADMIN_SCHEDULE_INVALID_MODE,
    ADNS_ADMIN_CNAME_CASCADE_FIND_ZONE_ERROR,
    ADNS_ADMIN_WILDCARD_FALLBACK_FIND_ZONE_ERROR,
    ADNS_ADMIN_CNAME_CASCADE_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_WILDCARD_FALLBACK_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_SHOW_MAX_ZONE_NUM_ERROR,
    ADNS_ADMIN_SHOW_MAX_DOMAIN_NUM_ERROR,
    ADNS_ADMIN_SHOW_MAX_RR_NUM_ERROR,
    ADNS_ADMIN_COUNTER_ERROR,
    ADNS_ADMIN_RCODE_STATS_ERROR,
    ADNS_ADMIN_RELOAD_IPLIB_ERROR,
    ADNS_ADMIN_RELOAD_VM_ERROR,
    ADNS_ADMIN_RELOAD_NSLIST_ERROR,
    ADNS_ADMIN_SHOW_NSLIST_ERROR,
    ADNS_ADMIN_LOOKUP_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_LOOKUP_DOMAIN_ERROR,
    ADNS_ADMIN_DUMP_OPEN_DUMP_FILE_ERROR,
    ADNS_ADMIN_DUMP_ZONEDB_TABLE_NULL_ERROR,
    ADNS_ADMIN_DUMP_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_DUMP_FIND_ZONE_ERROR,
    ADNS_ADMIN_DUMP_ZONE_META_ERROR,
    ADNS_ADMIN_DUMP_DNAME_ERROR,
    ADNS_ADMIN_DUMP_FIND_NODE_ERROR,
    ADNS_ADMIN_DUMP_NODE_NULL_ERROR,
    ADNS_ADMIN_DUMP_NODE_RDATA_ERROR,
    ADNS_ADMIN_CLEAR_ZONEDB_NULL_ERROR,
    ADNS_ADMIN_CLEAR_ZONEDB_TABLE_NULL_ERROR,
    ADNS_ADMIN_SHOW_MAX_PRIVATE_ROUTE_ZONE_NUM_ERROR,
    ADNS_ADMIN_SHOW_MAX_DNSSEC_ZONE_NUM_ERROR,
    ADNS_ADMIN_SHOW_MAX_DNSSEC_CACHE_NUM_ERROR,

    ADNS_ADMIN_REFRESH_ZONE_CONVERT_ZONE_ERROR = -500,
    ADNS_ADMIN_REFRESH_ZONE_CREATE_NEW_ERROR,
    ADNS_ADMIN_REFRESH_ZONE_NO_NEW_ERROR,
    ADNS_ADMIN_REFRESH_ZONE_SET_SCHED_ERROR,
    ADNS_ADMIN_REFRESH_ZONE_REPLACE_ERROR,
    ADNS_ADMIN_REFRESH_ZONE_RCU_REGISTER_ERROR,
    ADNS_ADMIN_REFRESH_ZONE_BATCH_SYNTAX_ERROR,
    ADNS_ADMIN_REFRESH_ZONE_RELOAD_ROUTE_ERROR,

    ADNS_ADMIN_REFRESH_DOMAIN_BATCH_SYNTAX_ERROR = -600,
    ADNS_ADMIN_REFRESH_DOMAIN_FIND_ZONE_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_FIND_NODE_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_ZONE_CONSISTENCY_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_NODE_CONSISTENCY_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_CONVERT_DOMAIN_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_CREATE_NEW_DOMAIN_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_NOT_SUB_DOMAIN_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_WILDCARD_NO_PARENT,
    ADNS_ADMIN_REFRESH_DOMAIN_REPLACE_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_RCU_REGISTER_ERROR,
    ADNS_ADMIN_REFRESH_DOMAIN_SET_SCHED_ERROR,

    /* ADMIN DNSSEC */
    ADNS_ADMIN_DNSSEC_FIND_ZONE_ERROR = -700,
    ADNS_ADMIN_DNSSEC_CONVERT_ZONE_ERROR,
    ADNS_ADMIN_DNSSEC_SET_ZONE_ERROR,
    ADNS_ADMIN_DNSSEC_ZONE_EXCEED_LIMIT_ERROR,
    ADNS_ADMIN_DNSSEC_ADD_KEY_ERROR,
    ADNS_ADMIN_DNSSEC_DEL_ZSK_ERROR,
    ADNS_ADMIN_DNSSEC_ADD_DNSKEY_RRSIG_ERROR,
    ADNS_ADMIN_DNSSEC_QUOTA_ERROR,
    ADNS_ADMIN_DNSSEC_CACHE_FLUSH_CONVERT_DOMAIN_ERROR,
    ADNS_ADMIN_DNSSEC_CACHE_FLUSH_VIEWID_ERROR,
    ADNS_ADMIN_DNSSEC_CACHE_DUMP_ERROR,
};


enum adns_error {
	ADNS_EOK = 0,             /*!< OK */

	/* TSIG errors. */
	ADNS_TSIG_EBADSIG = -16,  /*!< Failed to verify TSIG MAC. */
	ADNS_TSIG_EBADKEY = -17,  /*!< TSIG key not recognized or invalid. */
	ADNS_TSIG_EBADTIME = -18, /*!< TSIG signing time out of range. */

	/* Directly mapped error codes. */
	ADNS_ENOMEM = err2code(ENOMEM),             /*!< Out of memory. */
	ADNS_EINVAL = err2code(EINVAL),             /*!< Invalid parameter passed. */
	ADNS_ENOTSUP = err2code(ENOTSUP),           /*!< Parameter not supported. */
	ADNS_EBUSY = err2code(EBUSY),               /*!< Requested resource is busy. */
	ADNS_EAGAIN = err2code(EAGAIN),             /*!< OS lacked necessary resources. */
	ADNS_EACCES = err2code(EACCES),             /*!< Permission is denied. */
	ADNS_ECONNREFUSED = err2code(ECONNREFUSED), /*!< Connection is refused. */
	ADNS_EISCONN = err2code(EISCONN),           /*!< Already connected. */
	ADNS_EADDRINUSE = err2code(EADDRINUSE),     /*!< Address already in use. */
	ADNS_ENOENT = err2code(ENOENT),             /*!< Resource not found. */
	ADNS_ERANGE = err2code(ERANGE),             /*!< Value is out of range. */

	/* General errors. */
	ADNS_ERROR = -10000,  /*!< General error. */
	ADNS_ENOTRUNNING,     /*!< Resource is not running. */
	ADNS_EPARSEFAIL,      /*!< Parser fail. */
	ADNS_ENOIPV6,         /*!< No IPv6 support. */
	ADNS_EEXPIRED,        /*!< Resource is expired. */
	ADNS_EUPTODATE,       /*!< Zone is up-to-date. */
	ADNS_EFEWDATA,        /*!< Not enough data to parse. */
	ADNS_ESPACE,          /*!< Not enough space provided. */
	ADNS_EMALF,           /*!< Malformed data. */
	ADNS_ECRYPTO,         /*!< Error in crypto library. */
	ADNS_ENSEC3PAR,       /*!< Missing or wrong NSEC3PARAM record. */
	ADNS_ENSEC3CHAIN,     /*!< Missing or wrong NSEC3 chain in the zone. */
	ADNS_EOUTOFZONE,      /*!< Domain name does not belong to the zone. */
	ADNS_EHASH,           /*!< Error in hash table. */
	ADNS_EZONEINVAL,      /*!< Invalid zone file. */
	ADNS_ENOZONE,         /*!< No such zone found. */
	ADNS_ENONODE,         /*!< No such node in zone found. */
	ADNS_ENORRSET,        /*!< No such RRSet found. */
	ADNS_EDNAMEPTR,       /*!< Domain name pointer larger than allowed. */
	ADNS_EPAYLOAD,        /*!< Payload in OPT RR larger than max wire size. */
	ADNS_ECRC,            /*!< Wrong dump CRC. */
	ADNS_EPREREQ,         /*!< UPDATE prerequisity not met. */
	ADNS_ENOXFR,          /*!< Transfer was not sent. */
	ADNS_ENOIXFR,         /*!< Transfer is not IXFR (is in AXFR format). */
	ADNS_EXFRREFUSED,     /*!< Zone transfer refused by the server. */
	ADNS_EDENIED,         /*!< Not allowed. */
	ADNS_ECONN,           /*!< Connection reset. */
	ADNS_EIXFRSPACE,      /*!< IXFR reply did not fit in. */
	ADNS_ECNAME,          /*!< CNAME loop found in zone. */
	ADNS_ENODIFF,         /*!< No zone diff can be created. */
	ADNS_EDSDIGESTLEN,    /*!< DS digest length does not match digest type. */
	ADNS_ENOTSIG,         /*!< Expected a TSIG or SIG(0). */
	ADNS_ELIMIT,          /*!< Exceeded response rate limit. */
	ADNS_EWRITABLE,       /*!< File is not writable. */

	/* Control states. */
	ADNS_CTL_STOP,        /*!< Stop requested. */

	/* Network errors. */
	ADNS_NET_EADDR,
	ADNS_NET_ESOCKET,
	ADNS_NET_ECONNECT,
	ADNS_NET_ESEND,
	ADNS_NET_ERECV,
	ADNS_NET_ETIMEOUT,

	/* Encoding errors. */
	ADNS_BASE64_ESIZE,
	ADNS_BASE64_ECHAR,
	ADNS_BASE32HEX_ESIZE,
	ADNS_BASE32HEX_ECHAR,

	/* Key parsing errors. */
	ADNS_KEY_EPUBLIC_KEY_OPEN,
	ADNS_KEY_EPRIVATE_KEY_OPEN,
	ADNS_KEY_EPUBLIC_KEY_INVALID,

	/* Key signing errors. */
	ADNS_DNSSEC_ENOTSUP,
	ADNS_DNSSEC_EINVALID_KEY,
	ADNS_DNSSEC_EASSIGN_KEY,
	ADNS_DNSSEC_ECREATE_DIGEST_CONTEXT,
	ADNS_DNSSEC_EUNEXPECTED_SIGNATURE_SIZE,
	ADNS_DNSSEC_EDECODE_RAW_SIGNATURE,
	ADNS_DNSSEC_ESIGN
};


#endif 

