#ifndef _COMMON_VALUE_H_
#define _COMMON_VALUE_H_


enum ADNS_PKT_RCODE_COUNTER
{
	RCODE_NOERROR = 0,
	RCODE_FORMERR,
	RCODE_SERVFAIL,
	RCODE_NXDOMAIN,
	RCODE_NOTIMPL, /*Not implemented.*/
	RCODE_REFUSED,
	RCODE_YXDOMAIN,/*Name should not exist*/
	RCODE_YXRRSET, /*RR set should not exist*/
	RCODE_NXRRSET, /*RR set does not exist*/
	RCODE_NOTAUTH, /*Server not authoritative*/
	RCODE_NOTZONE, /*Name is not inside zone*/

	RCODE_BADSIG = 16,
	RCODE_BADKEY,
	RCODE_BADTIME,
	RCODE_BADMODE,
	RCODE_BADNAME,
	RCODE_BADALG,
	RCODE_BADTRUNC,

	ADNS_RCODE_COUNTER_MAX,
};

enum ADNS_PKT_DROP_COUNTER
{
	IPV4_HEADER_INVALID = 0,
    IPV6_HEADER_INVALID,
    IPV6_EXTHEADER_INVALID,
    ERROR_PORT,
	PACKAGE_BAD_LENGTH,
    PACKAGE_IS_RESPONSE,
    PARSE_DNS_WIRE_NULL_FAILED,
    UNSUPPORT_OPCODE,
    PACKAGE_DNS_HEAD_COUNT_FAILED,
    PACKAGE_EDNS_FORMAT_FAILED,
	FILL_DONE_PROCESS_FAILED,
	DEFAULT_VIEW_IS_NOT_EXISTED,
	VIEW_EXCEED_MAX_NUMBER,
	VIEW_NAME_IS_NOT_EXISTED,
	ANSWER_WITH_DEFAULT_FAILED,
	ANSWER_WITH_NORMAL_FAILED,
	DNSSEC_OVER_QUOTA,
	ADNS_PKT_DROP_COUNTER_MAX,
};


#endif
